version: "3"
services:
  database:
    image: postgres
    env_file:
      - ./config/dbConfigDocker.env
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data\ postgres
    ports:
      - "5432:5432"
    networks:
      - privateNetwork
      - publicNetwork
  app:
    build: .
    command: ["go", "run", "main.go"]
    volumes:
      - .:/app
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - publicNetwork
      - privateNetwork
networks:
  publicNetwork:
    internal: false
  privateNetwork:
    internal: true
volumes:
  postgres: